[package]
name = "rwf-ruby"
license = "MIT"
description = "Ruby (specifically Rack/Rails) bindings for Rwf"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
once_cell = "1"
thiserror = "1"
parking_lot = "0.9"
tracing = "0.1"

[build-dependencies]
cc = "1"
bindgen = "0.68"
