name: ci
on:
  push:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Format
        run: cargo fmt --all -- --check
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PostgreSQL
        run: |
          sudo sed -i 's/scram-sha-256/trust/g' /etc/postgresql/14/main/pg_hba.conf
          sudo service postgresql restart
          sudo -u postgres createuser --superuser --login $USER
          createdb $USER
          psql postgres://$USER@127.0.0.1:5432/$USER -c "SELECT 1" > /dev/null
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install test dependencies
        run: cargo install cargo-nextest cargo-expand
      - name: Run tests
        run: cargo nextest run
      - name: Run documentation tests
        run: cargo test --doc
