name: tests
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PostgreSQL
        run: |
          sudo cat /etc/postgresql/14/main/pg_hba.conf
          echo "peer all all peer" | sudo tee /etc/postgresql/14/main/pg_hba.conf
          echo "local all postgres peer" | sudo tee -a /etc/postgresql/14/main/pg_hba.conf
          echo "host all all 127.0.0.1/32 trust" | sudo tee -a /etc/postgresql/14/main/pg_hba.conf
          sudo service postgresql start
          sudo cat /etc/postgresql/14/main/pg_hba.conf
          sudo -u postgres createuser --superuser --login $USER
          createdb $USER
          psql postgres://$USER@127.0.0.1:5432/$USER -c "SELECT 1" > /dev/null
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build
      - name: Format
        run: cargo fmt --all -- --check
      - name: Install cargo-nextest
        run: cargo install cargo-nextest
      - name: Test
        run: cargo nextest run
